# Multi-Variable Linear Regression Example with Pytorch Models (다중 변수의 선형회귀)
- 국립한밭대학교 컴퓨터공학과 임경태
- https://sites.google.com/view/aailab

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x_train = np.array([[2, 3, 1], 
                    [4, 8, 9], 
                    [6, 2, 7], 
                    [8, 4, 6]])
y_train = np.array([[3], 
                    [7], 
                    [5], 
                    [8]])

n_samples = x_train.shape[0]
n_features = x_train.shape[1]
losses = []

In [3]:
import torch

In [9]:
linear_model = torch.nn.Linear(in_features=3, out_features=1) #input data 3개, output data 1개

print(linear_model)
print(list(linear_model.parameters()))

Linear(in_features=3, out_features=1, bias=True)
[Parameter containing:
tensor([[0.2641, 0.3605, 0.0692]], requires_grad=True), Parameter containing:
tensor([0.3477], requires_grad=True)]


In [10]:
x_train_torch = torch.from_numpy(x_train).float()
y_train_torch = torch.from_numpy(y_train).float()
print(x_train_torch)
print(x_train_torch.shape)

tensor([[2., 3., 1.],
        [4., 8., 9.],
        [6., 2., 7.],
        [8., 4., 6.]])
torch.Size([4, 3])


In [11]:
predicted_y = linear_model(x_train_torch) # linear_model.forword(x_train_torch)

In [12]:
optimizer = torch.optim.SGD(linear_model.parameters(), lr=0.01)
loss_function = torch.nn.MSELoss()

In [13]:
linear_model.train()
for idx in range(100):
  optimizer.zero_grad()
  predicted_y = linear_model(x_train_torch)
  loss = loss_function(predicted_y, y_train_torch)  
  print(loss.item())
  loss.backward()
  optimizer.step()


5.584649085998535
3.4197356700897217
2.1379265785217285
1.3750277757644653
0.9176383018493652
0.6406001448631287
0.4704189598560333
0.36386752128601074
0.295465886592865
0.25014951825141907
0.218977689743042
0.1966152936220169
0.17985717952251434
0.1667594611644745
0.15612979233264923
0.14722445607185364
0.13957154750823975
0.1328640878200531
0.12689664959907532
0.12152818590402603
0.11665775626897812
0.11221086978912354
0.1081313043832779
0.10437428951263428
0.10090409964323044
0.09769108891487122
0.09471041709184647
0.09194058179855347
0.08936305344104767
0.08696165680885315
0.08472177386283875
0.0826307162642479
0.08067670464515686
0.07884926348924637
0.07713890075683594
0.07553698122501373
0.07403544336557388
0.07262715697288513
0.07130542397499084
0.07006403803825378
0.06889709830284119
0.06779973953962326
0.06676676869392395
0.06579362601041794
0.06487647444009781
0.06401122361421585
0.06319427490234375
0.062422387301921844
0.06169232726097107
0.061001360416412354
0.0603467151522