# Neural Network with Quadratic Data
출처: https://github.com/GunhoChoi/PyTorch-FastCampus/blob/master/02_Regression%26NN/1_NN_code/1d_data/0_neural_quadratic.ipynb
- y = 8x^2+7x+3
- 4 hidden layers

<img src="./quadratic.png">

사진출처: http://cs.franklin.edu/~sieberth/MATH160/bookFiles/Chapter3/333371_0307_317-323.pdf 

## 1.Import Required Libraries

In [12]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.init as init
from torch.autograd import Variable
#from visdom import Visdom
#viz = Visdom()

## 2. Data Generation

In [13]:
num_data = 1000
num_epoch = 5000

noise = init.normal(torch.FloatTensor(num_data,1),std=3)

x = init.uniform(torch.Tensor(num_data,1),-15,15)
y = (x**2) + 3 

y_noise = y + noise

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  


In [14]:
# visualize data

input_data = torch.cat([x,y_noise],1)

#win=viz.scatter(
#    X = input_data,
#    opts=dict(
#        xtickmin=-15,
#        xtickmax=15,
#        xtickstep=1,
#        ytickmin=0,
#        ytickmax=500,
#        ytickstep=1,
#        markersymbol='dot',
#        markercolor=np.random.randint(0, 255, num_data),
#        markersize=5,
#    ),
#)


In [ ]:

win=#viz.scatter(
    X = torch.cat([x,y],1),
    opts=dict(
        xtickmin=-15,
        xtickmax=15,
        xtickstep=1,
        ytickmin=0,
        ytickmax=500,
        ytickstep=1,
        markersymbol='dot',
        markercolor=np.random.randint(0, 255, num_data),
        markersize=5,
    )#,
#)


## 3. Model & Optimizer

In [20]:
# fully connected model with 4 hidden layer

model = nn.Sequential(
        nn.Linear(1,120),
        nn.ReLU(),
        nn.Linear(120,360),
        nn.ReLU(),
        nn.Linear(360,720),
        nn.ReLU(),
        nn.Linear(720,360),
        nn.ReLU(),
        nn.Linear(360,1)
    )

loss_func = nn.L1Loss()
optimizer = optim.SGD(model.parameters(),lr=0.001)

## 4. Train 

In [21]:
loss_arr =[]
label = y_noise

for i in range(num_epoch):
    optimizer.zero_grad()
    output = model(x)

    loss = loss_func(output,label)
    loss.backward()
    optimizer.step()
    
    if i % 100 ==0:
        print(loss)
    
    #loss_arr.append(loss.cpu().data.numpy()[0])
    loss_arr.append(loss.item())

tensor(6.4418, grad_fn=<L1LossBackward0>)


KeyboardInterrupt: ignored

In [8]:
param_list = list(model.parameters())
print(param_list)

[Parameter containing:
tensor([[ 1.5345],
        [-1.2924],
        [ 2.9529],
        [-1.3849],
        [-1.9242],
        [-1.4047]], requires_grad=True), Parameter containing:
tensor([-0.0594,  0.2917, -1.4776, -2.0314, -2.2674, -2.0651],
       requires_grad=True), Parameter containing:
tensor([[1.3035, 0.8612, 3.1450, 2.1946, 2.7707, 2.3700]], requires_grad=True), Parameter containing:
tensor([-0.8573], requires_grad=True)]


## 5. Visualize Trained Output

In [ ]:
win2=#viz.scatter(
    X = torch.cat([x, output],1),
    opts=dict(
        xtickmin=-15,
        xtickmax=10,
        xtickstep=1,
        ytickmin=0,
        ytickmax=500,
        ytickstep=1,
        markersymbol='dot',
        markercolor=np.random.randint(0, 255, num_data),
        markersize=5,
    )#,
#)


## 6. Visualize Loss Graph

In [10]:
x = np.reshape([i for i in range(num_epoch)],newshape=[num_epoch,1])
loss_data = np.reshape(loss_arr,newshape=[num_epoch,1])

#win3=#viz.line(
#    X = x,
#    Y = loss_data,
#)"""