In [20]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
x_set = np.array([1,2,3,4,5,6])
x_set

array([1, 2, 3, 4, 5, 6])

In [5]:
def f(x):
    if x in x_set:
        return x / 21
    else:
        return 0

In [6]:
X = [x_set, f]
X

[array([1, 2, 3, 4, 5, 6]), <function __main__.f>]

In [11]:
prob = np.array([f(x_k) for x_k in x_set])
prob
dict(zip(x_set,prob))

{1: 0.047619047619047616,
 2: 0.09523809523809523,
 3: 0.14285714285714285,
 4: 0.19047619047619047,
 5: 0.23809523809523808,
 6: 0.2857142857142857}

In [12]:
x_set = np.arange(2,13)
y_set = np.arange(1,7)

In [18]:
def f_XY(x, y):
    if 1 <= y <= 6 and 1<= x - y <= 6:
        return y * (x-y) / 441
    else:
        return 0

print(x_set)
print(y_set)

[ 2  3  4  5  6  7  8  9 10 11 12]
[1 2 3 4 5 6]


In [19]:
XY = [x_set, y_set, f_XY]
prob = np.array([[f_XY(x_i, y_j) for y_j in y_set]
                 for x_i in x_set])
print(prob)

[[0.00226757 0.         0.         0.         0.         0.        ]
 [0.00453515 0.00453515 0.         0.         0.         0.        ]
 [0.00680272 0.00907029 0.00680272 0.         0.         0.        ]
 [0.00907029 0.01360544 0.01360544 0.00907029 0.         0.        ]
 [0.01133787 0.01814059 0.02040816 0.01814059 0.01133787 0.        ]
 [0.01360544 0.02267574 0.02721088 0.02721088 0.02267574 0.01360544]
 [0.         0.02721088 0.03401361 0.03628118 0.03401361 0.02721088]
 [0.         0.         0.04081633 0.04535147 0.04535147 0.04081633]
 [0.         0.         0.         0.05442177 0.05668934 0.05442177]
 [0.         0.         0.         0.         0.06802721 0.06802721]
 [0.         0.         0.         0.         0.         0.08163265]]


In [21]:
np.sum(prob)

1.0