In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
yashuo = np.array([2, 3, 1, 3])
okong = np.array([4, 8, 9, 7])
bl = np.array([6,2,7,5])
faker = np.array([8, 4, 6, 8])

In [28]:
x_train = np.array([[2, 3, 1],
                    [4, 8, 9],
                    [6, 2, 7],
                    [8, 4, 6]])
y_train = np.array([[3], [7], [5], [8]])

In [6]:
x_train.shape

(4, 3)

In [7]:
n_samples = x_train.shape[0]

In [8]:
n_features = x_train.shape[1]

In [9]:
n_samples


4

In [10]:
n_features

3

In [29]:
W = np.ones((3,1))
b = np.ones((1,1))

In [24]:
W.shape

(3, 1)

In [26]:
def f(X):
    return np.matmul(X,W) + b
#    return X[0]*w[0] + X[1]*w[1] + X[2]*w[2] + b
    

In [30]:
f(x_train)

array([[ 7.],
       [22.],
       [16.],
       [19.]])

In [35]:
def loss_function(y_pred, y_train):
    n_samples = y_train.shape[0]
    deviation = y_pred - y_train
    deviation_squred = deviation**2

    loss = (1/n_samples) * deviation_squred.sum()

    return deviation_squred

In [34]:
def gradient(x_train, y_train, y_pred):
    n_samples = y_train.shape[0]
    dw = (1/n_samples) * np.matmul(x_train.transpose(), (y_pred-y_train))

    return dw

In [33]:
def gradient_descent(W,learning_rate, dw):
    W = W - learning_rate * dw

In [22]:
dw = gradient(x_train, y_train, y_pred)

array([[4, 1],
       [2, 2]])

In [ ]:
gradient_descent(0.01, W, dw)

In [36]:
losses = []
for num_iter in range(100):
    #print("x_train : ", x_train)
    y_pred = f(x_train)
    loss = loss_function(y_pred, y_train)

    losses.append(loss)

    dw = gradient(x_train, y_train, y_pred)
    W = gradient_descent(0.01, W, dw)

    print(W)
    print(loss)

None
[[ 16.]
 [225.]
 [121.]
 [121.]]


ValueError: ignored