# Neural Network with 2D Data (2-dimensional)
- Neural Network with 4 layers
- 2D data f(x,y) -> R

## 1.Import Required Libraries

In [1]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.init as init
from torch.autograd import Variable
#from visdom import Visdom
#viz = Visdom()

## 2. Data Generation

In [2]:
num_data=1000
num_epoch=10000

x = init.uniform(torch.Tensor(num_data,1),-10,10)
y = init.uniform(torch.Tensor(num_data,1),-10,10)
z = x**2 + y**2

x_noise = x + init.normal(torch.FloatTensor(num_data,1),std=0.5)
y_noise = y + init.normal(torch.FloatTensor(num_data,1),std=0.5)
z_noise = x_noise**2 + y_noise**2

data_noise = torch.cat([x,y,z_noise],1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  if __name__ == '__main__':


In [ ]:
# data visualization
'''
win_1=viz.scatter(
        X=data_noise,
        opts=dict(
            markersize=5,
            markercolor=np.ndarray(shape=[num_data,3],dtype=float,buffer=[51,153,255]*np.ones(shape=[num_data,3]))
            )
        )
'''

## 3. Model & Optimizer

In [3]:
model = nn.Sequential(
            nn.Linear(2,20),
            nn.ReLU(),
            nn.Linear(20,10),
            nn.ReLU(),
            nn.Linear(10,5),
            nn.ReLU(),
            nn.Linear(5,5),
            nn.ReLU(),
            nn.Linear(5,1),
        )

loss_func = nn.L1Loss()
optimizer = optim.SGD(model.parameters(),lr=0.001)

## 4. Train 

In [5]:
input_data = torch.cat([x,y],1)
print(input_data)
print(input_data.size())
label = z_noise
loss_arr =[]

for i in range(num_epoch):
    optimizer.zero_grad()
    output = model(input_data)
    loss = loss_func(output,label)
    loss.backward()
    optimizer.step()
    
    loss_arr.append(loss.item())
    
    if i % 100 == 0 and i <1000:
        print(loss)
        data = torch.cat([input_data.cpu(),output.cpu().data],1)
      
#        win_2 =viz.scatter(
#                X=data,
#                opts=dict(
#                markersize=5,
#                markercolor=np.ndarray(shape=[num_data,3],dtype=float,buffer=128*np.ones(shape=[num_data,3]))
#            )
#    )

tensor([[-0.4775, -9.8042],
        [-1.1825, -2.9409],
        [-7.3808,  2.5466],
        ...,
        [-9.5117, -2.0003],
        [-6.1871,  1.3888],
        [ 4.6544, -7.8949]])
torch.Size([1000, 2])
tensor(5.8667, grad_fn=<L1LossBackward0>)
tensor(5.8311, grad_fn=<L1LossBackward0>)
tensor(6.0148, grad_fn=<L1LossBackward0>)
tensor(5.7364, grad_fn=<L1LossBackward0>)
tensor(5.8867, grad_fn=<L1LossBackward0>)
tensor(5.7403, grad_fn=<L1LossBackward0>)
tensor(6.0210, grad_fn=<L1LossBackward0>)
tensor(5.8238, grad_fn=<L1LossBackward0>)
tensor(5.8676, grad_fn=<L1LossBackward0>)
tensor(5.7115, grad_fn=<L1LossBackward0>)


In [6]:
param_list = list(model.parameters())
print(param_list)

[Parameter containing:
tensor([[-0.5311, -0.0723],
        [-0.0066,  0.4739],
        [-0.2977, -0.5986],
        [-0.0738,  0.4109],
        [-0.4271, -0.2820],
        [-0.3134, -0.0115],
        [ 0.6712, -0.3129],
        [-0.6921, -0.1278],
        [ 0.1818,  0.4482],
        [-0.6347,  0.3345],
        [-0.1327,  0.4770],
        [ 0.2550,  0.2014],
        [ 0.2971, -0.5434],
        [-0.0618, -0.3469],
        [-0.1885,  0.4517],
        [ 0.0692, -0.2666],
        [ 0.4484,  0.1728],
        [ 0.6710,  0.1647],
        [ 0.2344,  0.5705],
        [ 0.0520,  0.4181]], requires_grad=True), Parameter containing:
tensor([ 0.1145,  0.6106, -0.0240,  0.6741, -0.3534,  0.5426, -0.6989, -0.6088,
        -0.0150, -0.7902, -0.8905,  0.6366,  0.2471, -1.5776, -0.8338, -1.1200,
         0.2555, -0.9743, -1.2302,  0.6110], requires_grad=True), Parameter containing:
tensor([[-0.0533,  0.0504, -0.1898,  0.1085, -0.1288,  0.0017,  0.0116,  0.0081,
         -0.2200, -0.1353, -0.0920,  0.0703,

## 5. Visualize Trained Output

In [ ]:
data = torch.cat([input_data.cpu(),output.cpu().data],1)

win_2 =viz.scatter(
        X=data,
        opts=dict(
        markersize=5,
        markercolor=np.ndarray(shape=[num_data,3],dtype=float,buffer=128*np.ones(shape=[num_data,3]))
    )
)

## 6. Visualize Loss Graph

In [ ]:
x = np.reshape([i for i in range(num_epoch)],newshape=[num_epoch,1])
loss_data = np.reshape(loss_arr,newshape=[num_epoch,1])

win3=viz.line(
    X = x,
    Y = loss_data,
)